from backend.app.api.schemas.detection import (
    BoundingBox,
    DetectionItem,
    DetectionResponse,
    ImageDetectionConfig,
)
from backend.app.api.schemas.tracking import (
    TrackedItem,
    TrackingFrameResponse,
    TrackingConfig,
)
from backend.app.api.schemas.tracking_api import (
    TrackedItemResponse,
    VideoTrackingResponse,
)
from backend.app.api.schemas.analytics import (
    AnalyticsEvent,
    AnalyticsReport,
    AnalyticsSnapshot,
    ClassStatistics,
    LineCrossingEvent,
    LineDefinition,
    PerformanceMetrics,
    ROIDefinition,
    TrackStatistics,
    TrajectoryPoint,
)
from backend.app.api.schemas.system import (
    ConfigurationResponse,
    ErrorResponse,
    GPUInfo,
    HealthResponse,
    ModelInfo,
    SourcesResponse,
    StatusResponse,
)
from backend.app.api.schemas.websocket import (
    ClientAction,
    ClientCommand,
    ConnectionAckData,
    FrameResultData,
    ServerMessageType,
    StreamErrorData,
    StreamSourceType,
    StreamStartedData,
    StreamStoppedData,
    WebSocketMessage,
)

from backend.app.api.schemas.model import (
    ModelInfoResponse,
    ModelListResponse,
    ModelStatus,
    ModelSwitchRequest,
    ModelSwitchResponse,
    ModelType,
    ModelValidationResponse,
)

__all__ = [
    "BoundingBox",
    "DetectionItem",
    "DetectionResponse",
    "ImageDetectionConfig",
    "TrackedItem",
    "TrackingFrameResponse",
    "TrackingConfig",
    "TrackedItemResponse",
    "VideoTrackingResponse",
    "AnalyticsEvent",
    "AnalyticsReport",
    "AnalyticsSnapshot",
    "ClassStatistics",
    "LineCrossingEvent",
    "LineDefinition",
    "PerformanceMetrics",
    "ROIDefinition",
    "TrackStatistics",
    "TrajectoryPoint",
    "ConfigurationResponse",
    "ErrorResponse",
    "GPUInfo",
    "HealthResponse",
    "ModelInfo",
    "SourcesResponse",
    "StatusResponse",
    "ClientAction",
    "ClientCommand",
    "ConnectionAckData",
    "FrameResultData",
    "ServerMessageType",
    "StreamErrorData",
    "StreamSourceType",
    "StreamStartedData",
    "StreamStoppedData",
    "WebSocketMessage",
]
